# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:09
from __future__ import unicode_literals

from django.db import migrations
from play import load_player_data


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Stats', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(load_player_data),

    ]
